更新 增加se的最新爬虫和历史爬虫
masschaos/lottocrawler pull request #55
Opened 2020-08-27 03:32 UTC by superwunc

测试 抓取最新结果 见 test-crawler.js
测试 抓取历史结果 见 test-history.js

2020-08-27 04:18 UTC, hyacinthus commented
请 @mapleincode Review 一下，我把 review 准则写 readme 里了你应该已经见到了。

2020-08-27 05:10 UTC, mapleincode commented
收到

2020-08-27 11:14 UTC, guowenjia commented
lotto的那个彩种，好像没算那个winnerCount, 就是总中奖人数。

2020-08-27 12:07 UTC, superwunc commented
@guowenjia 我看example里的模型，只有keno有winerCount 字段，其他的没有，是其他都加winnerCount字段么？

2020-08-27 12:25 UTC, guowenjia commented
其他的不用加，因为这个我没注意网站有时候还有总中奖人数的情况，但网站上有就加一下吧，其他的两个没有看到有这个。

2020-08-27 13:17 UTC, guowenjia commented
除了上面的那个提到的winnerCount，我这边还有两个问题需要你看一下，其他的我这边没有发现问题。
1.  Vikinglotto  的号码拼接不太对
2.  Vikinglotto 的breakdown不太对。

我是直接从接口看的数据，不知道为啥我本地跑这个特别慢，不知道是不是网络的问题，下午用了很久才跑出来，晚上跑单个的也好久都跑不出来。下面这个是测试服的最新数据地址。
> https://seaapi.lottowawa.com/staging/results?country=se&level=0

2020-08-27 20:46 UTC, mapleincode requested changes

2020-08-27 20:46 UTC, mapleincode commented on crawler/se/api.js
> +}
这两段代码是不是功能重复了？

2020-08-27 20:46 UTC, mapleincode commented on crawler/se/api.js
> +}
建议这段代码扔到 util 里，因为使用率还挺高的

2020-08-27 20:49 UTC, mapleincode commented on crawler/se/api.js
> +}
@guowenjia 速度慢，是因为 @superwunc 担心网站被爬虫破坏。加了 8s 的延时。
这个我个人绝对没必要，只要单线程访问网站，一般很难导致网站被影响。而且这块主框架应该有处理。
具体你们商榷下？

爬取结果 @guowenjia 跑过了，那我就不跑了

2020-08-27 21:44 UTC, superwunc commented on crawler/se/api.js
> +}
8秒延迟那个，是抓取历史数据使用的，因为这个网站历史数据，是按照天，调用接口一天一天去请求的，抓取每天数据之间有个延迟
抓取最新数据，这块有个错误重试，最多重试3次，重试之间有个延迟5秒，如果没有必要可以给去掉
@guowenjia  速度慢，你是指抓取最新数据吧，应该是网络原因吧，我本地测试有时候也挺慢，有时候很快，但也不会慢的很离谱

2020-08-27 21:54 UTC, superwunc commented on crawler/se/api.js
> +}
已修正

2020-08-27 21:59 UTC, mapleincode commented on crawler/se/api.js
> +}
那应该是网速问题。
我倒没测试过 puppeeter 会不会自动走代理。我这边遇到的网站速度都还行。
如果不行的推荐一个神器  Proxifier，解决所有代理问题

2020-08-27 22:02 UTC, mapleincode approved these changes

2020-08-28 01:47 UTC, hyacinthus commented on crawler/se/api.js
> +}
重试延迟当然是必要的。 跑历史加上也没啥。

puppeeter 走代理比较麻烦，应该需要启动一个走了代理的 chrome，然后去连接那个chrome。

在 util 里边的time有个同步 sleep 函数，我在 stackoverflow 抄过来的。你们看看和 setTimeout 比有啥弊端，没有的话就用那个也行。

2020-08-28 01:54 UTC, mapleincode commented on crawler/se/api.js
> +}
Proxifier 神器，解决可以解决几乎所有 tcp 的代理问题，而且不需要应用支持 tcp。

你那个是封装过的一个包。但是我是支持 @superwunc 的写法，setTimeout 应该可以满足延迟的需求了

2020-08-28 02:11 UTC, superwunc commented on crawler/se/api.js
> +}
https://zhuanlan.zhihu.com/p/112126898 
这里对比延迟setTimout 和 Atomics.wait的区别，爬虫一般需要延迟的地方，应该是只针对当前调用，需要延迟，不影响其他的异步逻辑

2020-08-28 02:12 UTC, hyacinthus commented on crawler/se/api.js
> +}
不是的，我那个是原生支持没依赖……但是我也不太懂 看起来是一个hack吧 当时主要是为了在脚本顶层用 那时候不会在顶层 await 
```node
function sleep (ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms)
}
```

2020-08-28 02:20 UTC, mapleincode commented on crawler/se/api.js
> +}
这个文章提到一点，如果是并发爬取一个网站，在遇到网站崩溃或者错误时，期望所有的并发爬取都停下来。
那就用 Atomics。

如果是轮询爬取单个网站。两者区别不大。

但是如果并发爬取不同的网站。那 Atomics 会导致进程内所有的执行都会停止。而 setTimeout 只会导致在这个代码环境上下文的地方堵塞。

按目前的方式应该还是 setTimeout 合适点

2020-08-28 02:25 UTC, hyacinthus commented on crawler/se/api.js
> +}
刚好一个叫 sleep一个叫 wait ，你们可以往 util 里加多国需要使用的代码。

2020-08-28 12:11 UTC, merged