增加瑞典彩票的抓取
masschaos/lottocrawler pull request #60
Opened 2020-09-02 08:56 UTC by superwunc

验证脚本
 * node ./crawler/ch/tests/test-crawler.js ch-magic-3
 * node ./crawler/ch/tests/test-crawler.js ch-magic-4
 * node ./crawler/ch/tests/test-crawler.js ch-banco
 * node ./crawler/ch/tests/test-crawler.js ch-lotto
 * node ./crawler/ch/tests/test-crawler.js ch-euromillions
网站比较慢，翻墙会快一些
瑞典的彩票是2个网站
https://jeux.loro.ch 这个有API，API返回的是html片段，这个使用cheerio解析html
https://www.swisslos.ch 这个没有API，但是彩票的结果是直接html返回的，所以也使用cheerio解析html的方式

2020-09-03 03:14 UTC, guowenjia commented
ch-euromillions 彩种breakdown的name有些不对。其他的暂时没发现问题。

2020-09-03 03:46 UTC, superwunc commented
已修正 breakdown name 问题

2020-09-08 13:21 UTC, mapleincode requested changes

2020-09-08 14:22 UTC, superwunc commented on crawler/ch/api.js
> +  return [drawData]
这块解析彩票都返回数组，是因为有几个彩种，在一个response里可以解析出多期的彩票信息， 所以这2个只能解析出一期彩票信息的，返回也给包了一个数组，这块我增加一下注释

2020-09-08 15:45 UTC, mapleincode commented on crawler/ch/api.js
> +  return [drawData]
好的。如果统一那就没办法了。注释最好说明下返回的是数组

2020-09-08 15:46 UTC, mapleincode approved these changes

2020-09-10 10:29 UTC, merged