pe latestcraw and history
masschaos/lottocrawler pull request #64
Opened 2020-09-14 12:10 UTC by guowenjia

pe最新数据抓取及历史数据抓取

2020-09-14 18:01 UTC, mapleincode requested changes
```
[2020-09-14 17:21:31.908 +0000] INFO  (6707 on mac-mini.local): pe-tinka 获取最新结果出错: Evaluation failed: TypeError: Cannot read property 'innerText' of null
    at __puppeteer_evaluation_script__:2:61
    VError: pe-tinka 获取最新结果出错: Evaluation failed: TypeError: Cannot read property 'innerText' of null
        at __puppeteer_evaluation_script__:2:61
        at Object.crawl (/Users/maple/Desktop/SynologyDrive/masschaos/lottocrawler/crawler/pe/crawler/index.js:23:15)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

2020-09-14 18:01 UTC, mapleincode commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
pe-tinka 历史爬取出错。但是直接调用 index.js 好像没问题

2020-09-14 18:16 UTC, mapleincode commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
pe-tinka 存在 breakdown.detail 缺失数据（报错必现）
其他两个彩种 history 无问题。
三个彩种最新都无问题

2020-09-15 12:35 UTC, guowenjia commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
上面那个我改一下。 历史报错的问题没有处理，因为那个开奖时间是动态变化的，一段时间是周3，周六， 一段时间之后周六， 一段时间是周日和周日，没有专门的接口，网站上也没法判断，就把可能开奖的天一个一个的抓一次。不过那个不影响后面继续抓取历史数据。最新数据不会有这个问题，因为不用算是周几开奖。breakdown我看了一下抓取下来的历史好像不缺。

2020-09-15 18:24 UTC, mapleincode commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
搞错了， detail 缺失的是 `pe-kabala`。不过缺失的不多，有两个`detail":[]`你可以搜下，在结束位置

2020-09-15 18:25 UTC, mapleincode commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
![image](https://user-images.githubusercontent.com/8831159/93249425-defc9500-f7c3-11ea-9dad-0727f1d5e6cc.png)

2020-09-16 01:06 UTC, guowenjia commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
我查了一下，这个是网站上也没有这个数据。
![image](https://user-images.githubusercontent.com/27345371/93280310-e8095880-f7fb-11ea-981f-16684cea5883.png)

2020-09-16 01:21 UTC, mapleincode commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
那没有问题了

2020-09-16 01:44 UTC, guowenjia commented on crawler/pe/history.js
> +          config.indexPagePath = config.indexPagePath.split('?')[0] + `?del-dia=${queryTimeFormat}`
好的

2020-09-16 01:45 UTC, merged